### ISSUE TITLE
Error while running event

### ISSUE THREAD

**Issue by ghost** [mk-fg/games#1]
Happened after I died kind of?
http://prntscr.com/k191uv

**Comment by mk-fg** [comment]
Thanks for reporting it with a screenshot, definitely wouldn't have guessed what it was about otherwise.

control.lua:466 points to seemingly-unrelated `e.get_control_behavior().parameters = {parameters=params}` on wisp detectors, which doesn't even use any indexing, but it's factorio itself that raises that error when going through passed list of signals.
Apparently forgot to update "item_slot_count=3" on wisp detectors when adding 4th kind of wisps.

**Comment by mk-fg** [comment]
Should be fixed in 0.0.47.

**Comment by ghost** [comment]
Thank you! My server and I will be taking this mod for a spin tomorrow on a new map hopefully.
