### ISSUE TITLE
Error while running event

### ISSUE THREAD

**Issue by ghost** [mk-fg/games#2]
Happened randomly, not sure of cause, was only hour into the game.
http://prntscr.com/k1ef0f

**Comment by mk-fg** [comment]
Ah, damn it, looks like a cache invalidation error where chances for ForestSet chunks stay cached but set itself is modified just few lines after that, resulting in such bugs.
Cause is I think cutting trees en masse - `#trees >= conf.wisp_forest_min_density` check fails and cached chunk no longer considered a forest, yet get picked on the next iteration there by chance.

**Comment by mk-fg** [comment]
Should be fixed in 0.0.48, thanks again.

Sorry that it's not very production-ready, despite apparently 1k+ downloads by now - looks like me and other people aren't as good at running into these bugs or reporting them as you are.
There's always an option to wrap stuff in pcall() and hide these forever, but that doesn't seem like a good idea (at least for ones that can be spotted by just looking at the code), as then they'll never ever be fixed.

**Comment by ghost** [comment]
Oh not a problem man. I appreciate your work , this mod is really neat. I playtest mods way too much. I believe me hosting this in multiplayer on my server increases the chances of running into issues which is what happened with this earlier today as well. Cheers!
