### ISSUE TITLE
Power pole err. message

### ISSUE THREAD

**Issue by huncutj** [mk-fg/games#3]
Hi,
I made some circuit logic for filtering solar energy - when it triggered, this happened, what do think? :-) Thx.

![kép](https://user-images.githubusercontent.com/50463433/57481363-3c183a80-72a2-11e9-90a0-5a947758516e.png)

**Comment by mk-fg** [comment]
Almost certainly a bug in the mod, will look into it.

**Comment by mk-fg** [comment]
Error itself indicates that mod tried to set value above 2,147,483,647, which given that it's kW, should be ~2 TW of power measured. Which can't be right. Surely no one's base can be that huge.

**Comment by mk-fg** [comment]
Uploaded version 0.0.2 which instead of crashing on such weird values should cap them to 2^31-1 (that number above).

I think this might have happened at the moment when electrical grids were disconnected/reconnected, with power switch or wires/poles manually.
Grid stats are tracked in accumulative way in factorio, i.e. you get 0 values when start building a grid and each tick adds to that.
This mod tracks last values for connected grid per measurement pole, and these values get huge spike when e-grid that was running for a while gets suddenly connected to it, e.g. previous tick it was 12345 next tick it's 12345 * 10^6.

Now that values are capped, when connecting electrical grids like that, you'll get one-time spike in measured values (for 60 ticks / 1s at 1x, as circuit-poles update combinator values 1/60 ticks) instead of crash.

Guess mod can detect such spikes by some arbitrary threshold and filter them out, but that'd be error-prone and hiding information, plus you should be able to do that just as easily via decider combinator.
(or if you want something more powerful, check out https://mods.factorio.com/mod/LuaCombinator2 )

Thanks for reporting!
